info:
    author: beanyc
    report_version: v1.0
pre_process:
    switch: True
    size:
        rows: 6
        cols: 12
    origin_folder: '/data/el/tests/tests_detectron/jn_standard_testsets/img'
img_folder: '/data/el/tests/tests_detectron/jn_standard_testsets/img_cut'
output_folder: '/data/el/tests/tests_detectron/jn_standard_testsets/output1'
model:
    yinlie:
        threshold:
            yinlie: 0.9
            shixiao: 0.9
        model_dir: '/data/el/trains/trains_pytorch/jn_5BB_dan_full_yinlie_190617_r50'
    xuhan:
        threshold:
            xuhan: 0.9
        model_dir: '/data/el/trains/trains_pytorch/jn_5BB_dan_full_xuhan_190618'
auto_labeling:
    switch: False
post_process:
    switch: False
evaluation:
    switch: True
    csv_path: '/data/el/tests/tests_detectron/jn_standard_testsets/defect_location.csv'
    select_th:
        switch: True
        step: 0.01
        miss_number: 10
        overkill_number: 100000
